### ISSUE TITLE
EXPOSE 2112

### ISSUE THREAD

**Issue by gam6itko** [spacetab-io/docker-roadrunner-php#3]
Is it possible to expose port 2112? Spiral uses this port by defaul for prometheus metrics.

Look at `metrics` section of [config](https://github.com/spiral/roadrunner-docs/blob/1.0/intro/config.md)

**Comment by roquie** [comment]
if u want publish 2112 port u can use `--publish` flag for `docker run ...` command or `ports:` section in docker-compose.
