### ISSUE TITLE
Missing rr binary in 8.x spiral version

### ISSUE THREAD

**Issue by Norgul** [spacetab-io/docker-roadrunner-php#4]
Hello, I used the minimum Dockerfile recommended in readme to build an image:

```yaml
FROM spacetabio/roadrunner-alpine:8.0-spiral-1.8.0
COPY . /app
CMD ["rr", "serve", "-c", ".rr.yaml"]
```

Versions:
- `spacetabio/roadrunner-alpine:8.1-spiral-1.8.0`
- `spacetabio/roadrunner-alpine:8.0-spiral-1.8.0`

are erroring out with the message 
> /configure.sh: exec: line 13: rr: not found 

Which I could also reproduce by not using it on a project, but rather simply doing `docker build -t road . && docker exec -it road sh` and then within the prompt running `rr` which would return a command not found error.

Am I doing something wrong or is this a known issue?

**Comment by roquie** [comment]
For spiral images u should use `spiral` binary instead of `rr`
